services:
  jumpcloud-auth:
    image: thomseddon/traefik-forward-auth:latest
    container_name: stacksmith_jumpcloud-auth
    restart: unless-stopped
    environment:
      - DEFAULT_PROVIDER=oidc
      - PROVIDERS_OIDC_ISSUER_URL=https://oauth.id.jumpcloud.com
      - PROVIDERS_OIDC_CLIENT_ID=${JUMPCLOUD_CLIENT_ID}
      - PROVIDERS_OIDC_CLIENT_SECRET=${JUMPCLOUD_CLIENT_SECRET}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - SECRET=${AUTH_SECRET}
      - LOG_LEVEL=info
      - AUTH_HOST=${JUMPCLOUD_AUTH_HOSTNAME}
      - URL_PATH=/_oauth
    networks:
      - stacksmith
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jumpcloud-auth.rule=Host(`${JUMPCLOUD_AUTH_HOSTNAME}`)"
      - "traefik.http.routers.jumpcloud-auth.entrypoints=websecure"
      - "traefik.http.routers.jumpcloud-auth.tls.certresolver=stacksmith"
      - "traefik.http.services.jumpcloud-auth.loadbalancer.server.port=4181"

networks:
  stacksmith:
    external: true