services:
  jumpcloud-auth:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: stacksmith_jumpcloud-auth
    restart: unless-stopped
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://oauth.id.jumpcloud.com/
      - OAUTH2_PROXY_CLIENT_ID=${JUMPCLOUD_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${JUMPCLOUD_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - OAUTH2_PROXY_COOKIE_SECRET=${AUTH_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=https://${JUMPCLOUD_AUTH_HOSTNAME}/oauth2/callback
    networks:
      - stacksmith
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jumpcloud-auth.rule=Host(`${JUMPCLOUD_AUTH_HOSTNAME}`)"
      - "traefik.http.routers.jumpcloud-auth.entrypoints=websecure"
      - "traefik.http.routers.jumpcloud-auth.tls.certresolver=stacksmith"
      - "traefik.http.services.jumpcloud-auth.loadbalancer.server.port=4180"

networks:
  stacksmith:
    external: true