services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - LOG_LEVEL=DEBUG  # Enable for OAuth troubleshooting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOSTNAME}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=stacksmith"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  stacksmith:
    external: false

volumes:
  portainer-data: