services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: stacksmith_n8n
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=${TZ}
      - N8N_HOST=${N8N_HOSTNAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${N8N_HOSTNAME}
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - stacksmith
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`${N8N_HOSTNAME}`)"
      - "traefik.http.routers.n8n.entrypoints=websecure-tailscale"
      - "traefik.http.routers.n8n.tls.certresolver=stacksmith"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.middlewares=secure-headers@docker"

networks:
  stacksmith:
    external: true

volumes:
  n8n-data: