# Minimal Home Assistant Configuration
# This file provides only the essential configuration needed for Traefik integration
# All other configuration should be done through the Home Assistant UI after deployment

# Configure HTTP for reverse proxy (Traefik) - REQUIRED
http:
  # Required for reverse proxy setups
  use_x_forwarded_for: true
  # Trust the Docker network ranges where Traefik runs
  trusted_proxies:
    - 172.18.0.0/16
    - 172.19.0.0/16
    - 172.20.0.0/16
    - 172.21.0.0/16

# Default configuration - Home Assistant will prompt for setup via UI
default_config: