services:
  pihole:
    image: pihole/pihole:latest
    container_name: stacksmith_pihole
    restart: unless-stopped
    networks:
      - stacksmith
    ports:
      - "${PIHOLE_HOST_IP}:${PIHOLE_DNS_PORT:-53}:53/tcp"
      - "${PIHOLE_HOST_IP}:${PIHOLE_DNS_PORT:-53}:53/udp"
    extra_hosts:
      - "${PIHOLE_HOSTNAME}:${PIHOLE_HOST_IP}"
    environment:
      TZ: "${TZ:-UTC}"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "${PIHOLE_DNS_UPSTREAMS:-1.1.1.1;1.0.0.1;9.9.9.9;149.112.112.112}"
      FTLCONF_webserver_port: "${PIHOLE_WEB_PORT:-8080}"
      DHCP_ACTIVE: false
    volumes:
      - pihole-config:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_HOSTNAME}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=stacksmith"
      - "traefik.http.routers.pihole.middlewares=jumpcloud-auth@docker"
      - "traefik.http.services.pihole.loadbalancer.server.port=${PIHOLE_WEB_PORT:-8080}"

networks:
  stacksmith:
    external: true

volumes:
  pihole-config:
  pihole-dnsmasq: