theme: dark
jwt_secret: ${AUTHELIA_JWT_SECRET}
default_redirection_url: https://${PORTAINER_HOSTNAME}

server:
  host: 0.0.0.0
  port: 9091

log:
  level: warn

duo_api:
  hostname: ${DUO_API_HOSTNAME}
  integration_key: ${DUO_INTEGRATION_KEY}
  secret_key: ${DUO_SECRET_KEY}

totp:
  issuer: ${PORTAINER_HOSTNAME}

authentication_backend:
  password_reset:
    disable: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 512
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: "*.${PORTAINER_HOSTNAME}"
      policy: two_factor
      methods:
        - duo

session:
  name: authelia_session
  secret: ${AUTHELIA_SESSION_SECRET}
  expiration: 3600
  inactivity: 300
  domain: ${PORTAINER_HOSTNAME}

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    sender: ${SMTP_SENDER}
    startup_check_address: test@authelia.com