services:
  traefik:
    image: traefik:latest
    container_name: stacksmith_traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.stacksmith.acme.dnschallenge=true
      - --certificatesresolvers.stacksmith.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.stacksmith.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.stacksmith.acme.storage=/letsencrypt/acme.json
    ports:
      - "${TRAEFIK_INTERFACE:-0.0.0.0}:80:80"
      - "${TRAEFIK_INTERFACE:-0.0.0.0}:443:443"
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_DYNAMIC_DIR:-./dynamic}:/etc/traefik/dynamic:ro
      - traefik-certificates:/letsencrypt
    networks:
      - stacksmith
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=stacksmith"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.middlewares=jumpcloud-auth"
      - "traefik.http.middlewares.jumpcloud-auth.forwardauth.address=https://${JUMPCLOUD_AUTH_HOSTNAME}/_oauth"
      - "traefik.http.middlewares.jumpcloud-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.jumpcloud-auth.forwardauth.authResponseHeaders=X-Forwarded-User,X-Forwarded-Email,X-Forwarded-Groups"

networks:
  stacksmith:
    name: stacksmith
    external: true

volumes:
  traefik-certificates: