services:
  mem-store:
    image: qdrant/qdrant:latest
    container_name: stacksmith_mem_store
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - mem-storage:/qdrant/storage
    networks:
      - mem-internal
    ports:
      - "6333:6333"

  mem:
    image: mem0/openmemory-mcp:latest
    container_name: stacksmith_mem
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USER=${MEM_USER}
      - QDRANT_HOST=mem-store
      - QDRANT_PORT=6333
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - mem-store
    networks:
      - stacksmith
      - mem-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mem.rule=Host(`${MEM_HOSTNAME}`)"
      - "traefik.http.routers.mem.entrypoints=websecure-tailscale"
      - "traefik.http.routers.mem.tls.certresolver=stacksmith"
      - "traefik.http.services.mem.loadbalancer.server.port=8765"
      - "traefik.http.routers.mem.middlewares=secure-headers@docker"

volumes:
  mem-storage:
    name: stacksmith_mem_storage

networks:
  stacksmith:
    external: true
  mem-internal:
    driver: bridge