http:
  routers:
    lmstudio:
      rule: Host(`lmstudio.example.com`)
      entryPoints:
        - websecure-tailscale
      service: lmstudio
      tls:
        certResolver: stacksmith
      middlewares:
        - secure-headers@docker

  services:
    lmstudio:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:1234"
