services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: stacksmith_qdrant
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - openmemory-storage:/qdrant/storage
    networks:
      - stacksmith

  openmemory:
    image: mem0/openmemory-mcp:latest
    container_name: stacksmith_openmemory
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USER=${OPENMEMORY_USER}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - qdrant
    networks:
      - stacksmith
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openmemory-api.rule=Host(`${OPENMEMORY_HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.openmemory-api.entrypoints=websecure-tailscale"
      - "traefik.http.routers.openmemory-api.tls.certresolver=stacksmith"
      - "traefik.http.services.openmemory-api.loadbalancer.server.port=8765"
      - "traefik.http.routers.openmemory-api.middlewares=secure-headers@docker"

  openmemory-ui:
    image: mem0/openmemory-ui:latest
    container_name: stacksmith_openmemory_ui
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=https://${OPENMEMORY_HOSTNAME}/api
      - NEXT_PUBLIC_USER_ID=${OPENMEMORY_USER}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      - openmemory
    networks:
      - stacksmith
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openmemory-ui.rule=Host(`${OPENMEMORY_HOSTNAME}`)"
      - "traefik.http.routers.openmemory-ui.entrypoints=websecure-tailscale"
      - "traefik.http.routers.openmemory-ui.tls.certresolver=stacksmith"
      - "traefik.http.services.openmemory-ui.loadbalancer.server.port=3000"
      - "traefik.http.routers.openmemory-ui.middlewares=secure-headers@docker"
      - "traefik.http.routers.openmemory-ui.priority=1"

volumes:
  openmemory-storage:
    name: stacksmith_openmemory_storage

networks:
  stacksmith:
    external: true