services:
  ghost:
    image: ghost:${GHOST_VERSION:-6-alpine}
    container_name: stacksmith_ghost
    restart: unless-stopped
    environment:
      # Database configuration
      database__client: mysql
      database__connection__host: stacksmith_ghost_db
      database__connection__user: ghost
      database__connection__password: ${DATABASE_PASSWORD}
      database__connection__database: ghost
      # URL configuration
      url: https://${GHOST_PUBLIC_HOSTNAME}
      # Admin URL for Tailscale access
      admin__url: https://${GHOST_ADMIN_HOSTNAME}
      # Mail configuration
      mail__transport: SMTP
      mail__options__service: ${MAIL_SERVICE}
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT}
      mail__options__secure: ${MAIL_SECURE}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASSWORD}
      mail__from: ${MAIL_FROM}
      # Timezone
      TZ: ${TZ}
    volumes:
      - ghost-content:/var/lib/ghost/content
    networks:
      - stacksmith
    labels:
      # Admin interface via Tailscale
      - "traefik.enable=true"
      - "traefik.http.routers.ghost-admin.rule=Host(`${GHOST_ADMIN_HOSTNAME}`)"
      - "traefik.http.routers.ghost-admin.entrypoints=websecure-tailscale"
      - "traefik.http.routers.ghost-admin.tls.certresolver=stacksmith"
      - "traefik.http.routers.ghost-admin.service=ghost"
      - "traefik.http.routers.ghost-admin.middlewares=ghost-admin-redirect"
      # Redirect root to /ghost/ for convenience
      - "traefik.http.middlewares.ghost-admin-redirect.redirectregex.regex=^https://([^/]+)/?$$"
      - "traefik.http.middlewares.ghost-admin-redirect.redirectregex.replacement=https://$${1}/ghost/"
      # Public interface via secondary entrypoint
      - "traefik.http.routers.ghost-public.rule=Host(`${GHOST_PUBLIC_HOSTNAME}`) && !PathPrefix(`/ghost`)"
      - "traefik.http.routers.ghost-public.entrypoints=websecure-secondary"
      - "traefik.http.routers.ghost-public.tls.certresolver=stacksmith"
      - "traefik.http.routers.ghost-public.service=ghost"
      - "traefik.http.routers.ghost-public.middlewares=secure-headers@docker"
      # Shared service configuration
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
    depends_on:
      - ghost-db

  ghost-db:
    image: mysql:8.0
    container_name: stacksmith_ghost_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ghost-db:/var/lib/mysql
    networks:
      - stacksmith
    command: --default-authentication-plugin=mysql_native_password

volumes:
  ghost-content:
    name: stacksmith_ghost_content
  ghost-db:
    name: stacksmith_ghost_db

networks:
  stacksmith:
    external: true
